### ISSUE TITLE
Unable to make predictions with pretrained models

### ISSUE THREAD

**Issue by iaposto** [IBM/AutoPeptideML#33]
Hello!

Following installation, I am trying to make predictions using your pretrained models downloaded from [Zenodo Repository](https://zenodo.org/records/13363975/files/AutoPeptideML_SI.tar.gz?download=1). 
I am using for example`autopeptideml peptide_dataset.csv --ensemble AutoPeptideML_SI/HPO_NegSearch_HP/DPPIV_1` and I get `autopeptideml: error: unrecognized arguments: --ensemble /AutoPeptideML_SI/HPO_NegSearch_HP/DPPIV_1`

I am specifically interested in DPPIV since the pretrained model does not seem to be available in the [webserver](http://peptide.ucd.ie/AutoPeptideML).

Thanks in advance for your help!

**Comment by iaposto** [comment]
After doing some digging, I found that the correct command is `autopeptdeml-predict` (sorry about that!)

I am now using:
```
autopeptdeml-predict --ensemble /autopeptideml/AutoPeptideML_SI/HPO_NegSearch_HP/DPPIV_1/ensemble --outputdir /autopeptideml /peptides.csv
```
where `peptides.csv` has only one column names `sequence`

I am now getting this error:
```
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 11.53it/s]
/miniconda3/envs/autopeptideml/lib/python3.13/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator KNeighborsClassifier from version 1.3.0 when using version 1.5.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "/miniconda3/envs/autopeptideml/bin/autopeptdeml-predict", line 8, in <module>
    sys.exit(predict())
             ~~~~~~~^^
  File "/miniconda3/envs/autopeptideml/lib/python3.13/site-packages/autopeptideml/main.py", line 159, in predict
    apml.predict(df, re, args.ensemble, args.outputdir)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/autopeptideml/lib/python3.13/site-packages/autopeptideml/autopeptideml.py", line 635, in predict
    clf = joblib.load(model_path)
  File "/miniconda3/envs/autopeptideml/lib/python3.13/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/miniconda3/envs/autopeptideml/lib/python3.13/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/miniconda3/envs/autopeptideml/lib/python3.13/pickle.py", line 1255, in load
    dispatch[key[0]](self)
    ~~~~~~~~^^^^^^^^
KeyError: 0
```

Any thoughts? Thanks!

**Comment by iaposto** [comment]
It seems that the issue is with the `joblib` package. I am using `python=3.10` and `scikit-learn==1.3.0`
```
Python 3.10.15
Type "help", "copyright", "credits" or "license" for more information.
>>> import joblib
>>> model = joblib.load('/autopeptideml/AutoPeptideML_SI/HPO_NegSearch_HP/DPPIV_1/ensemble/._K-Nearest Neighbours_0.joblib')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/autopeptideml-compat/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/miniconda3/envs/autopeptideml-compat/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/miniconda3/envs/autopeptideml-compat/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
KeyError: 0
```
Can you please confirm which `joblib` version worked for you?

**Comment by RaulFD-creator** [comment]
I am using `joblib==1.4.2` and `python=3.12.6`, but I don't think Python is the issue.

**Comment by iaposto** [comment]
Thanks for the prompt response!
I am also using `joblib==1.4.2` so that's strange.
Regarding your comment, unfortunately DPP-IV is not available in the webserver.

**Comment by RaulFD-creator** [comment]
I really don't know what it may be. I have included the `DPPIV` to the webserver. I missed it when setting it up. Apologies. I will continue investigating whether there is a solution to the `joblib` issue or to make the predictors easier to use in the different versions and environments.

**Comment by iaposto** [comment]
Thank you for uploading DPPIV to the webserver and for investigating this issue.

**Comment by RaulFD-creator** [comment]
@iaposto, I think that I figured out a solution to the `joblib` compatibility issue.

I have changed the model storage backend to `onnx` which does not rely on the `sklearn` version, but saves a stable object that can be used without calls to the Python code. I think this should be enough to get around the problem you were having. I have updated the version of the models in the Zenodo archive [v.2](https://zenodo.org/records/14591403).

Both models with the `joblib` and `onnx` backends are supported. If you (or anyone) wants to update `joblib` models to `onnx` models you can just run `apml-predict` on a ensemble with `joblib` and it will automatically update it to `onnx`. If you want to keep the models as `joblib` you can use the new `model-save-backend` flag and set it to `joblib`.

```bash
apml-predict dataset.csv --ensemble ./ensemble --save-model-backend joblib
```

I will release a new patch to the `pip` package v.1.0.5 in the coming weeks. If you want to use the new backend before you can install it directly from source:

```bash
pip install git+https://github.com/IBM/AutoPeptideML
```

Please, let me know if this solves your issue (I haven't been able to reproduce it in my machine -it may be an OS compatibility issue as well).
